version: '3'
services:
  database:
    image: "postgres:12.3"
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  spring:
    image: "demo/spring-graphql"
    container_name: spring
    depends_on:
      - database
    ports:
      - 8080:8080