graphql:
  packages:
    - "com.andreramon.demo"
  subscriptions:
    # Send a ka message every 1000 ms (1 second)
    keepAliveInterval: 1000

spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost/postgres"
    username: "postgres"
    password: "password"