graphql:
  packages:
    - "com.andreramon.demo"

spring:
  r2dbc:
    # 'database' represents container name in docker-compose.yml
    url: "r2dbc:postgresql://database/postgres"
    username: "postgres"
    password: "password"